### PR TITLE
[v10; iOS] Support Offline Raster Styles

### LINKED ISSUE #2169: Raster Tiles aren't saved via OfflineManager
## Environment

- Mapbox (GL) implementation: v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version #main
- Platform: iOS
- React Native Version 0.68
- Platform OS: iOS 15
- Device: any
- Emulator/ Simulator: yes
- Dev OS: Monterey

## Standalone component to reproduce

```js
import React from 'react';
import {StyleSheet, View} from 'react-native';
import MapboxGL from '@rnmapbox/maps';

const styles = StyleSheet.create({
    mapView: {flex: 1},
});

class BugExample extends React.Component {
    constructor(props) {
      super(props);

      this.state = {
        showMap: false, // change to true to show map
      };
    }

    async componentDidMount() {
        // delete for testing
        // console.log(await MapboxGL.offlineManager.deletePack('field-1'));

        console.log('>>>>>>>>>>start creating pack', );
        await MapboxGL.offlineManager.createPack(
            {
                name: 'field-1', // any
                bounds: [[32.23782523101579, 46.39912398458027], [33.43887899585923, 47.041693870480955]], // any LARGE area
                styleURL: MapboxGL.StyleURL.Satellite,
                minZoom: 10,
                maxZoom: 12,
            },
            (pack, status) => {
                console.log('>>>>>>>>>>pack progress', pack.name, status.percentage, status.completedTileCount);
            },
            (pack, error) => {
                console.log('>>>>>>>>>>pack error', pack.name, error);
            },
        );

        console.log(await MapboxGL.offlineManager.getPacks());
    }

    render() {
        // change showMap to true to render map when offline (wifi off / airplane mode) to test offline loading of tiles
        if (!this.state.showMap) return <View />;

        return (
            <View style={styles.mapView}>
                <MapboxGL.MapView
                    ref={(c) => (this._map = c)}
                    onPress={this.onPress}
                    style={styles.mapView}
                    styleURL={MapboxGL.StyleURL.Satellite}
                >
                    <MapboxGL.Camera
                        zoomLevel={10}
                        centerCoordinate={[33.43887899585923, 47.041693870480955]}
                    />
                </MapboxGL.MapView>
            </View>
        );
    }
}

export default BugExample;
}
```

## Observed behavior and steps to reproduce

Any raster style (eg; Satellite or SatelliteStreet) is able to be downloaded successfully; however, when loaded offline the raster images aren't rendered. The vector assets are rendered successfully (streets, city names, etc). The rest of the map is blurry as it is unable to load the raster images.

1. start sample app & wait until download is complete
2. go offline
3. flip `state.showMap` to true
4. Map is rendered without raster tiles and only shows vector assets

## Expected behavior

Raster tiles should be rendered when offline.

## Notes / preliminary analysis

The map pack is created successfully for a raster style; however, it doesn't seem like the raster assets are actually downloaded.

EDIT: It appears the iOS code is outdated and the zoom range needs to be passed in the TilesetDescriptorOptions. Android appears to still be broken however.

### PR DESCRIPTION
**Pull request by wen-kai**
## Description
[iOS only] Supports downloading of regions with raster styles (satellite).
Updated TilesetDescriptorOptions to use supported parameters (https://docs.mapbox.com/ios/maps/api/10.7.0/Extensions/TilesetDescriptorOptions.html#/s:So27MBMTilesetDescriptorOptionsC10MapboxMapsE8styleURI9zoomRange10pixelRatio0f4PackC0AbC05StyleG0V_SNys5UInt8VGSfSo08MBMStylel4LoadC0CSgtcfc).

Fixes #2169 

## Checklist

- [x ] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

### CODE REVIEW

File: ios/RCTMGL-v10/RCTMGLOfflineModule.swift [hunk 1]
```diff
@@ -321,26 +321,24 @@ class RCTMGLOfflineModule: RCTEventEmitter {
   func createPack(_ options: NSDictionary, resolver: @escaping RCTPromiseResolveBlock, rejecter: @escaping RCTPromiseRejectBlock) {
     DispatchQueue.main.async {
       do {
+        let metadataStr = options["metadata"] as! String
+        let metadata = try JSONSerialization.jsonObject(with: metadataStr.data(using: .utf8)!, options: []) as! [String:Any]
+        let id = metadata["name"] as! String
+        let stylePackLoadOptions = StylePackLoadOptions(glyphsRasterizationMode: .ideographsRasterizedLocally, metadata: ["tag": id])!
```
Comment (mfazekas) [inline ios/RCTMGL-v10/RCTMGLOfflineModule.swift:327]:
```suggestion
        let stylePackLoadOptions = StylePackLoadOptions(glyphsRasterizationMode: .ideographsRasterizedLocally, metadata: metadata)
```

Unless there is a reason for not storing the full metadata

**Review by mfazekas — APPROVED** [review]
