### PR TITLE
fix(android): Prevent Error thrown on null values for layer Id's

### LINKED ISSUE #2158: v10 Android: Passing null via aboveLayerID prop throws error
Passing null as a value for aboveLayerID / belowLayerID on Android throws an error of 

```
Exception in native call
com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'aboveLayerID' of a view managed by: RCTMGLSymbolLayer
```

This was not an issue prior to the v10 updates.

## Environment

- @rnmapbox/maps #main
- Platform: Android

## Standalone component to reproduce

```js
import React from 'react';
import { Button } from 'react-native';
import {
  MapView,
  ShapeSource,
  SymbolLayer,
  CircleLayer,
  Camera,
} from '@rnmapbox/maps';

const styles = {
  mapView: { flex: 1 },
  circleLayer: {
    circleRadiusTransition: { duration: 5000, delay: 0 },
    circleColor: '#ff0000',
  },
};

const features = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: 'a-feature',
      properties: {
        icon: 'example',
        text: 'example-icon-and-label',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.00597, 40.71427],
      },
    },
    {
      type: 'Feature',
      id: 'b-feature',
      properties: {
        text: 'just-label',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.001097, 40.71527],
      },
    },
    {
      type: 'Feature',
      id: 'c-feature',
      properties: {
        icon: 'example',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.00697, 40.72427],
      },
    },
  ],
};

class BugReportExample extends React.Component {
  state = {
    radius: 20,
  };

  render() {
    const circleLayerStyle = {
      ...styles.circleLayer,
      ...{ circleRadius: this.state.radius },
    };

    return (
      <>
        <Button
          title="Grow"
          onPress={() => this.setState({ radius: this.state.radius + 20 })}
        />
        <MapView style={styles.mapView}>
          <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
          <ShapeSource id={'shape-source-id-0'} shape={features}>
            <CircleLayer id={'circle-layer'} style={circleLayerStyle} aboveLayerID={null} />
          </ShapeSource>
        </MapView>
      </>
    );
  }
}

export default BugReportExample;
```

### PR DESCRIPTION
**Pull request by Gnative**
## Description
The new v10 on Android throws an error when passing null values to the aboveLayerID and belowLayerID props on. This wasn't a problem on the pervious version.

Fixes #2158

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

### CODE REVIEW

File: android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt [hunk 1]
```diff
@@ -49,7 +49,7 @@ abstract class RCTLayer<T : Layer?>(protected var mContext: Context) : AbstractS
         mSourceID = sourceID
     }
 
-    fun setAboveLayerID(aboveLayerID: String) {
+    fun setAboveLayerID(aboveLayerID: String?) {
```
Comment (mfazekas) [inline android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt:52]: Not sure if it works in case aboveLayerID was non-nill then cleared to nil

Comment (Gnative) [reply android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/styles/layers/RCTLayer.kt:52]: Cool. I'll take a look.

**Comment by Gnative** [comment]
This looks to be working now with a small tweak

```js

import React from 'react';
import { Button } from 'react-native';
import {
  MapView,
  ShapeSource,
  SymbolLayer,
  CircleLayer,
  Camera,
} from '@rnmapbox/maps';

const styles = {
  mapView: { flex: 1 },
  circleLayer: {
    circleRadiusTransition: { duration: 5000, delay: 0 },
    circleColor: '#ff0000',
  },
};

const features = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      id: 'a-feature',
      properties: {
        icon: 'example',
        text: 'example-icon-and-label',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.00597, 40.71427],
      },
    },
    {
      type: 'Feature',
      id: 'b-feature',
      properties: {
        text: 'just-label',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.001097, 40.71527],
      },
    },
    {
      type: 'Feature',
      id: 'c-feature',
      properties: {
        icon: 'example',
      },
      geometry: {
        type: 'Point',
        coordinates: [-74.00697, 40.72427],
      },
    },
  ],
};

const LAYER_ID = 'road-secondary-tertiary'

class BugReportExample extends React.Component {
  state = {
    radius: 20,
    belowLayerID: LAYER_ID,
  };

  render() {
    const circleLayerStyle = {
      ...styles.circleLayer,
      ...{ circleRadius: this.state.radius },
    };

    return (
        <>
          <Button
              title="Grow"
              onPress={() => this.setState({ radius: this.state.radius + 20 })}
          />
          <Button
              title={`Set belowLayerID to ${ this.state.belowLayerID == null  ? LAYER_ID : null}`}
              onPress={() => this.setState({ belowLayerID: this.state.belowLayerID == null ? LAYER_ID : null })}
          />
          <MapView style={styles.mapView}>
            <Camera centerCoordinate={[-74.00597, 40.71427]} zoomLevel={14} />
            <ShapeSource id={'shape-source-id-0'} shape={features}>
              <CircleLayer id={'circle-layer'} style={circleLayerStyle} belowLayerID={this.state.belowLayerID}  />
              <SymbolLayer
                  id="symbol-id"
                  style={{
                    iconImage: ['get', 'icon'],
                  }}
              />
            </ShapeSource>
          </MapView>
        </>
    );
  }
}

export default BugReportExample;

```

**Review by mfazekas — APPROVED** [review]

**Comment by Gnative** [comment]
@mfazekas not sure why this is failing on `iOS/MapLibre` I tested this locally and it ran fine. Considering this Pull Request only dealt with Android is this a CI fault ?

I've rebased to current #main

**Comment by mfazekas** [comment]
> @mfazekas not sure why this is failing on `iOS/MapLibre` I tested this locally and it ran fine. Considering this Pull Request only dealt with Android is this a CI fault ?
> 
> I've rebased to current #main

Sometime we see test failure regarding cocoapods/EOF on the CI

**Review by mfazekas — APPROVED** [review]
