### PR TITLE
fix(android,v10): setCamera padding with center

### LINKED ISSUE #2339: [Bug]: Padding not applied when used alone in `setCamera` on Android
### Mapbox Implementation

Mapbox

### Mapbox Version

10.9.0

### Platform

Android

### `@rnmapbox/maps` version

10.0.0-beta.49

### Standalone component to reproduce

```typescript
import React, { memo, useEffect, useRef, useState } from 'react';
import { Button, Text } from 'react-native';
import MBGL, { MapView, Logger, Camera } from '@rnmapbox/maps';

import Page from '../common/Page';
import { BaseExampleProps } from '../common/BaseExamplePropTypes';

Logger.setLogLevel('verbose');

const PaddingBugReproduction = memo((props: BaseExampleProps) => {
  const cameraRef = useRef<Camera>(null);
  const [padding, setPadding] = useState(0);

  useEffect(() => {
    if (!cameraRef.current) return;

    cameraRef.current.setCamera({
      padding: {
        paddingTop: 0,
        paddingRight: 0,
        paddingBottom: 0,
        paddingLeft: padding,
      },
    });
  });

  return (
    <Page {...props}>
      <Button title={'Set 0 padding'} onPress={() => setPadding(0)} />
      <Button title={'Set 100 padding'} onPress={() => setPadding(100)} />
      <Text style={{ color: 'black', textAlign: 'center' }}>
        Current padding: {padding}
      </Text>
      <MapView
        style={{ flex: 1 }}
        projection="mercator"
        styleURL={MBGL.StyleURL.Street}
      >
        <Camera
          ref={cameraRef}
          zoomLevel={2}
          pitch={0}
          animationDuration={0}
          centerCoordinate={[20, 40]}
        />
      </MapView>
    </Page>
  );
});

export default PaddingBugReproduction;
```

### Observed behavior and steps to reproduce

**Android**
Android Padding Bug mp4 10-26

**IOS (Working)**
IOS Padding Working mp4 10-26

### Expected behavior

I expect the map to shift when padding is applied, just like on IOS.

### Notes / preliminary analysis

Seems like adding `bounds` to the `setCamera` call makes it work, but adding `centerCoordinate` does not.

### Additional links and references

_No response_

### PR DESCRIPTION
**Pull request by KiwiKilian**
## Description

Fixes #2339

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I updated the typings files - if js interface was changed (`index.d.ts`)
- [ ] I added/ updated a sample - if a new feature was implemented (`/example`)

## Screenshot OR Video

https://user-images.githubusercontent.com/18724559/223556338-7c28fe0a-a5ce-4099-ba53-646e6b52284b.mp4

Example used:
```tsx
import React, { useRef, useState } from 'react';
import { Button, View } from 'react-native';
import MapboxGL, {
  Camera,
  CircleLayer,
  MapView,
  ShapeSource,
} from '@rnmapbox/maps';
import { Point, Polygon } from 'geojson';

import FillLayer = MapboxGL.FillLayer;

const CENTER_POINT: Point = { type: 'Point', coordinates: [8.5, 50.5] };
const BOUNDS: Polygon = {
  type: 'Polygon',
  coordinates: [
    [
      [9.0, 50.0],
      [8.0, 50.0],
      [8.0, 51.0],
      [9.0, 51.0],
      [9.0, 50.0],
    ],
  ],
};

const styles = {
  mapView: { flex: 1 },
};

const BugReportExample = () => {
  const cameraRef = useRef<Camera>(null);
  const [mode, setMode] = useState<'center' | 'bounds'>('center');
  const [padding, setPadding] = useState(0);

  const setCenter = (paddingBottom: number) => {
    setMode('center');
    setPadding(paddingBottom);
    cameraRef.current?.setCamera({
      centerCoordinate: CENTER_POINT.coordinates,
      zoomLevel: 7,
      padding: {
        paddingTop: 0,
        paddingRight: 0,
        paddingBottom,
        paddingLeft: 0,
      },
    });
  };

  const setBounds = (paddingBottom: number) => {
    setMode('bounds');
    setPadding(paddingBottom);
    cameraRef.current?.setCamera({
      bounds: {
        ne: [9.0, 50.0],
        sw: [8.0, 51.0],
        // paddingTop: 0,
        // paddingRight: 0,
        paddingBottom,
        // paddingLeft: 0,
      },
    });
  };

  return (
    <>
      <Button title="Center with padding 0" onPress={() => setCenter(0)} />
      <Button title="Center with padding 300" onPress={() => setCenter(300)} />
      <Button title="Bounds with padding 0" onPress={() => setBounds(0)} />
      <Button title="Bounds with padding 300" onPress={() => setBounds(300)} />
      <MapView style={styles.mapView}>
        <Camera
          ref={cameraRef}
          defaultSettings={{
            centerCoordinate: CENTER_POINT.coordinates,
            zoomLevel: 7,
          }}
        />

        <ShapeSource id="center-source" shape={CENTER_POINT}>
          <CircleLayer
            id="center-circle"
            style={{
              visibility: mode === 'center' ? 'visible' : 'none',
              circleColor: 'red',
              circleRadius: 16,
            }}
          />
        </ShapeSource>

        <ShapeSource id="bounds-source" shape={BOUNDS}>
          <FillLayer
            id="bounds-fill"
            style={{
              visibility: mode === 'bounds' ? 'visible' : 'none',
              fillOutlineColor: 'black',
              fillColor: '#FF000080',
            }}
          />
        </ShapeSource>
      </MapView>
      <View
        style={{
          position: 'absolute',
          right: 0,
          bottom: 0,
          left: 0,
          height: padding,
          backgroundColor: '#00FF0080',
        }}
      />
    </>
  );
};

export default BugReportExample;
```

### CODE REVIEW

File: android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt [hunk 1]
```diff
@@ -110,33 +108,39 @@ import com.mapbox.mapboxsdk.maps.MapboxMap;
         if (mTilt != null) {
             builder.pitch(mTilt)
         }
+
+        val paddingLeft: Int = mPaddingLeft ?: currentPadding.left.toInt()
+        val paddingTop: Int = mPaddingTop ?: currentPadding.top.toInt()
+        val paddingRight: Int = mPaddingRight ?: currentPadding.right.toInt()
+        val paddingBottom: Int = mPaddingBottom ?: currentPadding.bottom.toInt()
```
Comment (KiwiKilian) [inline android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt:115]: @mfazekas  This fallback retrieval from `currentPadding` is once again regarding the [topic of `contentInset` etc.](https://github.com/rnmapbox/maps/issues/2554#issuecomment-1406210302) – should we get rid of this and simply require to pass the padding every time when e.g. calling `setCamera`?

Comment (mfazekas) [reply android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt:115]: I'd say let's keep this now.

setCamera is used by a lot of functions like zoomTo, etc. and then those would need to pass the current padding as well. We could allow `paddingLeft: `current` ` which means it'll use the padding currently used. Or a new padding property that could be either a `padding: {bottom: 10}`, or `padding: 'current'`. Not sure.

Comment (KiwiKilian) [reply android/rctmgl/src/main/java-v10/com/mapbox/rctmgl/components/camera/CameraStop.kt:115]: What's important, we should be making sure this behavior is the same on Android and iOS. Furthermore this does currently not work, because in `Camera.tsx` function `buildNativeStop` creates the padding values like this:
```ts
_nativeStop.paddingTop = stop.padding?.paddingTop ?? stop.bounds?.paddingTop ?? 0;
_nativeStop.paddingRight = stop.padding?.paddingRight ?? stop.bounds?.paddingRight ?? 0;
_nativeStop.paddingBottom = stop.padding?.paddingBottom ?? stop.bounds?.paddingBottom ?? 0;
_nativeStop.paddingLeft = stop.padding?.paddingLeft ?? stop.bounds?.paddingLeft ?? 0;
```
