### PR TITLE
fix(android): requestDisallowInterceptTouchEvent broken

### LINKED ISSUE #3326: [Bug]: requestDisallowInterceptTouchEvent broken
### Mapbox Implementation

Mapbox

### Mapbox Version

10.16.1

### Platform

Android

### `@rnmapbox/maps` version

10.1.6

### Standalone component to reproduce

```javascript
import React from 'react';
import {
  MapView
} from '@rnmapbox/maps';

class BugReport extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}} requestDisallowInterceptTouchEvent={true}>
      </MapView>
    );
  }
}
```

### Observed behavior and steps to reproduce

A runtime error occurs as soon `requestDisallowInterceptTouchEvent` is set.
Screenshot_1705501458

### Expected behavior

_No response_

### Notes / preliminary analysis

_No response_

### Additional links and references

_No response_

### PR DESCRIPTION
**Pull request by VolkerLieber**
## Description

Fixes #3326 by waiting until mMapView has been initialized.

### CODE REVIEW

**Review by mfazekas — APPROVED** [review]

File: android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt [hunk 1]
```diff
@@ -327,7 +327,9 @@ open class RNMBXMapViewManager(context: ReactApplicationContext, val viewTagReso
 
     @ReactProp(name = "requestDisallowInterceptTouchEvent")
     override fun setRequestDisallowInterceptTouchEvent(mapView: RNMBXMapView, requestDisallowInterceptTouchEvent: Dynamic) {
-        mapView.requestDisallowInterceptTouchEvent = requestDisallowInterceptTouchEvent.asBoolean()
+        mapView.withMapView {
+            it.requestDisallowInterceptTouchEvent = requestDisallowInterceptTouchEvent.asBoolean()
```
Comment (mfazekas) [inline android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt:331]:
```suggestion
            it.requestDisallowInterceptTouchEvent = mapView.requestDisallowInterceptTouchEvent
```

**Review by mfazekas — APPROVED** [review]

File: android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt (hunk 1 above)
Comment (VolkerLieber) [reply android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt:331]: Would that not just be `x = x` ?

Comment (mfazekas) [reply android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt:331]: Variable naming is a bit confusing there. ‘it’ is mapbox’s MapView, mapView is RNMBXMapView

Comment (VolkerLieber) [reply android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt]: My bad, I have to admit, that I tried to fix this issue while being on the go.  I've now correctly set up the development environment and my new commit seems to be the best solution for me.

```
@ReactProp(name = "requestDisallowInterceptTouchEvent")
override fun setRequestDisallowInterceptTouchEvent(mapView: RNMBXMapView, requestDisallowInterceptTouchEvent: Dynamic) {
    mapView.requestDisallowInterceptTouchEvent = requestDisallowInterceptTouchEvent.asBoolean()
}
```
Calls
```
var requestDisallowInterceptTouchEvent: Boolean = false
    set(value) {
        val oldValue = field
        field = value
        updateRequestDisallowInterceptTouchEvent(oldValue, value)
    }
```
Which calls
```
fun RNMBXMapView.updateRequestDisallowInterceptTouchEvent(oldValue: Boolean, value: Boolean) {
    if (oldValue == value) {
        return
    }
    if (value) {
        mapView.setOnTouchListener { view, event ->
            this.requestDisallowInterceptTouchEvent(true)
            mapView.onTouchEvent(event)
            true
        }
    } else {
        mapView.setOnTouchListener { view, event ->
            mapView.onTouchEvent(event)
        }
    }
}
```
The issue arises, because `mapView` is not initialized then `mapView.setOnTouchListener` is first called. By wrapping it with `withMapView`, this should be fixed.

What do you think?

**Review by mfazekas — APPROVED** [review]

File: android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt (hunk 1 above)
Comment (mfazekas) [reply android/src/main/java/com/rnmapbox/rnmbx/components/mapview/RNMBXMapViewManager.kt]: Looks good
