### PR TITLE
iOS: Fix crash when adding/removing map subview

### LINKED ISSUE #2062: [v10] example app crashes on iOS in user location example
**Describe the bug**  
The example app crashes on iOS when the user location is set to native.

**To Reproduce**  

    git checkout 6d266f7c3d707941a380733630b1dbf561780c48
    cd example
    yarn 
    yarn ios

Click on "User Location", then "Set User Location Render Mode", then click on "native".
=> app crashes

````
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: F8754E59-7907-4D42-BCBB-8A1231051852
CrashReporter Key:   693231DD-25A9-466D-9257-A92E8BF1F9B3
Hardware Model:      Mac13,1
Process:             RNMapboxGLExample [95561]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/C276C5CB-97F6-4816-A1BD-DF1433F9702C/data/Containers/Bundle/Application/BA4E62F7-B6E3-456C-BB13-B550DAF2A704/RNMapboxGLExample.app/RNMapboxGLExample
Identifier:          org.reactjs.native.example.RNMapboxGLExample
Version:             1.0 (1)
Code Type:           X86-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [35951]
Coalition:           com.apple.CoreSimulator.SimDevice.C276C5CB-97F6-4816-A1BD-DF1433F9702C [7327]
Responsible Process: SimulatorTrampoline [15097]

Date/Time:           2022-07-21 20:03:54.0955 +0200
Launch Time:         2022-07-21 20:03:38.2692 +0200
OS Version:          macOS 12.5 (21G72)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: SIGNAL 4 Illegal instruction: 4
Terminating Process: exc handler [95561]

Triggered by Thread:  0

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   <translation info unavailable>	       0x10f1a2754 ???
1   <translation info unavailable>	       0x107e45054 ???
2   libswiftCore.dylib            	       0x116f6984b closure #1 in closure #1 in _assertionFailure(_:_:file:line:flags:) + 267
3   libswiftCore.dylib            	       0x116f6963d closure #1 in _assertionFailure(_:_:file:line:flags:) + 333
4   libswiftCore.dylib            	       0x116f691b5 _assertionFailure(_:_:file:line:flags:) + 309
5   RNMapboxGLExample             	       0x10594920c RCTMGLMapView.addToMap(_:) + 1820 (RCTMGLMapView.swift:53)
6   RNMapboxGLExample             	       0x105949ea9 RCTMGLMapView.insertReactSubview(_:at:) + 249 (RCTMGLMapView.swift:75)
7   RNMapboxGLExample             	       0x105949f4d @objc RCTMGLMapView.insertReactSubview(_:at:) + 61
8   RNMapboxGLExample             	       0x10565c156 -[RCTUIManager _manageChildren:moveFromIndices:moveToIndices:addChildReactTags:addAtIndices:removeAtIndices:registry:] + 2502 (RCTUIManager.m:968)
9   RNMapboxGLExample             	       0x10565b5d5 __108-[RCTUIManager manageChildren:moveFromIndices:moveToIndices:addChildReactTags:addAtIndices:removeAtIndices:]_block_invoke + 133 (RCTUIManager.m:906)
10  RNMapboxGLExample             	       0x10565ede6 __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke + 374 (RCTUIManager.m:1198)
11  RNMapboxGLExample             	       0x10565f0fc __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.498 + 396 (RCTUIManager.m:1218)
12  RNMapboxGLExample             	       0x10566761d __RCTExecuteOnMainQueue_block_invoke + 29 (RCTUtils.m:265)
13  libdispatch.dylib             	       0x11534e8e4 _dispatch_call_block_and_release + 12
14  libdispatch.dylib             	       0x11534fb25 _dispatch_client_callout + 8
15  libdispatch.dylib             	       0x11535d043 _dispatch_main_queue_drain + 1050
16  libdispatch.dylib             	       0x11535cc1b _dispatch_main_queue_callback_4CF + 31
17  CoreFoundation                	       0x112208ed5 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
18  CoreFoundation                	       0x1122036ca __CFRunLoopRun + 2761
19  CoreFoundation                	       0x112202704 CFRunLoopRunSpecific + 562
20  GraphicsServices              	       0x118116c8e GSEventRunModal + 139
21  UIKitCore                     	       0x12278465a -[UIApplication _run] + 928
22  UIKitCore                     	       0x1227892b5 UIApplicationMain + 101
23  RNMapboxGLExample             	       0x104ff5888 main + 104 (main.m:15)
24  dyld_sim                      	       0x110400f21 start_sim + 10
25  dyld                          	       0x20800a52e start + 462

Thread 1:: com.apple.rosetta.exceptionserver
0   ???                           	    0x7ff7ffe63944 ???
1   ???                           	    0x7ff7ffe7c1f0 ???

Thread 2:
0   ???                           	    0x7ff7ffe81814 ???

Thread 3:
0   ???                           	    0x7ff7ffe81814 ???

Thread 4:: com.apple.uikit.eventfetch-thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x107dffa94 ???
2   libsystem_kernel.dylib        	       0x117985ce8 mach_msg + 56
3   CoreFoundation                	       0x112208acc __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	       0x1122030e2 __CFRunLoopRun + 1249
5   CoreFoundation                	       0x112202704 CFRunLoopRunSpecific + 562
6   Foundation                    	       0x11425a049 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 213
7   Foundation                    	       0x11425a2c2 -[NSRunLoop(NSRunLoop) runUntilDate:] + 72
8   UIKitCore                     	       0x122847bda -[UIEventFetcher threadMain] + 491
9   Foundation                    	       0x1142831a1 __NSThread__start__ + 1009
10  libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
11  libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 5:
0   ???                           	    0x7ff7ffe81814 ???

Thread 6:
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108798464 ???
2   RNMapboxGLExample             	       0x1058d0c14 kq_dispatch + 436 (kqueue.c:315)
3   RNMapboxGLExample             	       0x1058bfef7 event_base_loop + 679 (event.c:1992)
4   RNMapboxGLExample             	       0x10519f83f (anonymous namespace)::EventBaseBackend::eb_event_base_loop(int) + 31 (EventBase.cpp:73)
5   RNMapboxGLExample             	       0x105194e4e folly::EventBase::loopBody(int, bool) + 1662 (EventBase.cpp:359)
6   RNMapboxGLExample             	       0x105194787 folly::EventBase::loop() + 87 (EventBase.cpp:283)
7   RNMapboxGLExample             	       0x105196fe2 folly::EventBase::loopForever() + 98 (EventBase.cpp:497)
8   RNMapboxGLExample             	       0x1052be639 folly::run(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&) + 153 (ScopedEventBaseThread.cpp:40)
9   RNMapboxGLExample             	       0x1052c2b0e decltype(static_cast<void (*>(fp)(static_cast<folly::EventBaseManager*>(fp0), static_cast<folly::EventBase*>(fp0), static_cast<folly::Baton<true, std::__1::atomic>*>(fp0), static_cast<folly::Range<char const*>>(fp0))) std::__1::__invoke<void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> >(void (*&&)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*&&, folly::EventBase*&&, folly::Baton<true, std::__1::atomic>*&&, folly::Range<char const*>&&) + 62 (type_traits:3918)
10  RNMapboxGLExample             	       0x1052c2a89 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*>, 2ul, 3ul, 4ul, 5ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> >&, std::__1::__tuple_indices<2ul, 3ul, 4ul, 5ul>) + 137 (thread:287)
11  RNMapboxGLExample             	       0x1052c2042 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> > >(void*) + 98 (thread:298)
12  libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
13  libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 7:
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108798464 ???
2   RNMapboxGLExample             	       0x1058d0c14 kq_dispatch + 436 (kqueue.c:315)
3   RNMapboxGLExample             	       0x1058bfef7 event_base_loop + 679 (event.c:1992)
4   RNMapboxGLExample             	       0x10519f83f (anonymous namespace)::EventBaseBackend::eb_event_base_loop(int) + 31 (EventBase.cpp:73)
5   RNMapboxGLExample             	       0x105194e4e folly::EventBase::loopBody(int, bool) + 1662 (EventBase.cpp:359)
6   RNMapboxGLExample             	       0x105194787 folly::EventBase::loop() + 87 (EventBase.cpp:283)
7   RNMapboxGLExample             	       0x105196fe2 folly::EventBase::loopForever() + 98 (EventBase.cpp:497)
8   RNMapboxGLExample             	       0x1052be639 folly::run(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&) + 153 (ScopedEventBaseThread.cpp:40)
9   RNMapboxGLExample             	       0x1052c2b0e decltype(static_cast<void (*>(fp)(static_cast<folly::EventBaseManager*>(fp0), static_cast<folly::EventBase*>(fp0), static_cast<folly::Baton<true, std::__1::atomic>*>(fp0), static_cast<folly::Range<char const*>>(fp0))) std::__1::__invoke<void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> >(void (*&&)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*&&, folly::EventBase*&&, folly::Baton<true, std::__1::atomic>*&&, folly::Range<char const*>&&) + 62 (type_traits:3918)
10  RNMapboxGLExample             	       0x1052c2a89 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*>, 2ul, 3ul, 4ul, 5ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> >&, std::__1::__tuple_indices<2ul, 3ul, 4ul, 5ul>) + 137 (thread:287)
11  RNMapboxGLExample             	       0x1052c2042 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (*)(folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> const&), folly::EventBaseManager*, folly::EventBase*, folly::Baton<true, std::__1::atomic>*, folly::Range<char const*> > >(void*) + 98 (thread:298)
12  libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
13  libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 8:: FutureTimekeepr
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108798464 ???
2   RNMapboxGLExample             	       0x1058d0c14 kq_dispatch + 436 (kqueue.c:315)
3   RNMapboxGLExample             	       0x1058bfef7 event_base_loop + 679 (event.c:1992)
4   RNMapboxGLExample             	       0x10519f83f (anonymous namespace)::EventBaseBackend::eb_event_base_loop(int) + 31 (EventBase.cpp:73)
5   RNMapboxGLExample             	       0x105194e4e folly::EventBase::loopBody(int, bool) + 1662 (EventBase.cpp:359)
6   RNMapboxGLExample             	       0x105194787 folly::EventBase::loop() + 87 (EventBase.cpp:283)
7   RNMapboxGLExample             	       0x105196fe2 folly::EventBase::loopForever() + 98 (EventBase.cpp:497)
8   RNMapboxGLExample             	       0x105331b7c folly::ThreadWheelTimekeeper::ThreadWheelTimekeeper()::$_3::operator()() const + 28 (ThreadWheelTimekeeper.cpp:33)
9   RNMapboxGLExample             	       0x105331b25 decltype(static_cast<folly::ThreadWheelTimekeeper::ThreadWheelTimekeeper()::$_3>(fp)()) std::__1::__invoke<folly::ThreadWheelTimekeeper::ThreadWheelTimekeeper()::$_3>(folly::ThreadWheelTimekeeper::ThreadWheelTimekeeper()::$_3&&) + 21 (type_traits:3918)
10  RNMapboxGLExample             	       0x105331ac5 void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, folly::ThreadWheelTimekeeper::ThreadWheelTimekeeper()::$_3>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, folly::ThreadWheelTimekeeper::ThreadWheelTimekeeper()::$_3>&, std::__1::__tuple_indices<>) + 37 (thread:287)
11  RNMapboxGLExample             	       0x105331372 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, folly::ThreadWheelTimekeeper::ThreadWheelTimekeeper()::$_3> >(void*) + 98 (thread:298)
12  libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
13  libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 9:: com.facebook.SocketRocket.NetworkThread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x107dffa94 ???
2   libsystem_kernel.dylib        	       0x117985ce8 mach_msg + 56
3   CoreFoundation                	       0x112208acc __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	       0x1122030e2 __CFRunLoopRun + 1249
5   CoreFoundation                	       0x112202704 CFRunLoopRunSpecific + 562
6   Foundation                    	       0x11425a049 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 213
7   RNMapboxGLExample             	       0x105871ceb -[SRRunLoopThread main] + 267 (SRRunLoopThread.m:70)
8   Foundation                    	       0x1142831a1 __NSThread__start__ + 1009
9   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
10  libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 10:: com.apple.NSURLConnectionLoader
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x107dffa94 ???
2   libsystem_kernel.dylib        	       0x117985ce8 mach_msg + 56
3   CoreFoundation                	       0x112208acc __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	       0x1122030e2 __CFRunLoopRun + 1249
5   CoreFoundation                	       0x112202704 CFRunLoopRunSpecific + 562
6   CFNetwork                     	       0x111e113e0 0x111bdd000 + 2311136
7   Foundation                    	       0x1142831a1 __NSThread__start__ + 1009
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 11:: com.facebook.react.JavaScript
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x107dffa94 ???
2   libsystem_kernel.dylib        	       0x117985ce8 mach_msg + 56
3   CoreFoundation                	       0x112208acc __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	       0x1122030e2 __CFRunLoopRun + 1249
5   CoreFoundation                	       0x112202704 CFRunLoopRunSpecific + 562
6   RNMapboxGLExample             	       0x105581a65 +[RCTCxxBridge runRunLoop] + 949 (RCTCxxBridge.mm:378)
7   Foundation                    	       0x1142831a1 __NSThread__start__ + 1009
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 12:: JavaScriptCore libpas scavenger
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x115557334 scavenger_thread_main + 1684
4   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
5   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 13:
0   ???                           	    0x7ff7ffe81814 ???

Thread 14:: com.apple.CFStream.LegacyThread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x107dffa94 ???
2   libsystem_kernel.dylib        	       0x117985ce8 mach_msg + 56
3   CoreFoundation                	       0x112208acc __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	       0x1122030e2 __CFRunLoopRun + 1249
5   CoreFoundation                	       0x112202704 CFRunLoopRunSpecific + 562
6   CoreFoundation                	       0x11222c266 _legacyStreamRunLoop_workThread + 249
7   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
8   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 15:
0   ???                           	    0x7ff7ffe81814 ???

Thread 16:: com.squareup.SocketRocket.NetworkThread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x107dffa94 ???
2   libsystem_kernel.dylib        	       0x117985ce8 mach_msg + 56
3   CoreFoundation                	       0x112208acc __CFRunLoopServiceMachPort + 319
4   CoreFoundation                	       0x1122030e2 __CFRunLoopRun + 1249
5   CoreFoundation                	       0x112202704 CFRunLoopRunSpecific + 562
6   Foundation                    	       0x11425a049 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 213
7   RNMapboxGLExample             	       0x1056449c2 -[_RCTSRRunLoopThread main] + 338 (RCTSRWebSocket.m:1624)
8   Foundation                    	       0x1142831a1 __NSThread__start__ + 1009
9   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
10  libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 17:: com.apple.CFSocket.private
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x109d46f1c ???
2   CoreFoundation                	       0x11221d8f4 __CFSocketManager + 647
3   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
4   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 18:: JIT Worklist Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 19:: JIT Worklist Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 20:: JIT Worklist Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 21:: com.mapbox.common.Worker 1
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 22:: com.mapbox.common.Worker 2
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 23:: com.mapbox.common.Worker 3
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 24:: com.mapbox.common.Worker 4
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 25:: com.mapbox.common.AssetFileSource
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 26:: com.mapbox.common.TileStoreFileSource
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 27:: com.mapbox.common.LocalFileSource
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 28:: com.mapbox.common.OnlineFileSource
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e6c3 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) + 93
4   MapboxCommon                  	       0x1113c96bb std::__1::cv_status std::__1::condition_variable::wait_until<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::steady_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > > const&) + 171
5   MapboxCommon                  	       0x1113cd8f0 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 528
6   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
7   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 29:: com.mapbox.common.ResourceLoaderThread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   libc++.1.dylib                	       0x11030e632 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 18
4   MapboxCommon                  	       0x1113cd93f void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, mapbox::common::ThreadedSchedulerBase::makeSchedulerThread(unsigned long, mapbox::base::WeakPtr<mapbox::common::Scheduler>, mapbox::common::ThreadServiceType)::$_0> >(void*) + 607
5   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
6   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 30:
0   ???                           	    0x7ff7ffe81814 ???

Thread 31:
0   ???                           	    0x7ff7ffe81814 ???

Thread 32:
0   ???                           	    0x7ff7ffe81814 ???

Thread 33:
0   ???                           	    0x7ff7ffe81814 ???

Thread 34:: Heap Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 35:: Heap Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 36:: Heap Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 37:: Heap Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 38:: Heap Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 39:: Heap Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15

Thread 40:: Heap Helper Thread
0   ???                           	       0x107d74940 ???
1   <translation info unavailable>	       0x108bdd8ec ???
2   libsystem_pthread.dylib       	       0x1178a0a6f _pthread_cond_wait + 1249
3   JavaScriptCore                	       0x1154adf57 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2279
4   JavaScriptCore                	       0x115474d0f bool WTF::Condition::waitUntilUnchecked<WTF::Lock>(WTF::Lock&, WTF::TimeWithDynamicClockType const&) + 143
5   JavaScriptCore                	       0x115475103 WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 323
6   JavaScriptCore                	       0x1154d1055 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 357
7   JavaScriptCore                	       0x1154d37b9 WTF::wtfThreadEntryPoint(void*) + 9
8   libsystem_pthread.dylib       	       0x1178a04e1 _pthread_start + 125
9   libsystem_pthread.dylib       	       0x11789bf6b thread_start + 15


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000000de426832  rbx: 0x0000000000000000  rcx: 0x00000000de426832  rdx: 0x00000000de627046
  rdi: 0x0000000000000032  rsi: 0x000060000394d9e0  rbp: 0x00000003110ab8a0  rsp: 0x00000003110ab890
   r8: 0x00000000000019e0   r9: 0x0000000000000060  r10: 0x00000000000007fb  r11: 0x00000000000000a9
  r12: 0x00000001153abd02  r13: 0x00000003110abc40  r14: 0x0000000000000035  r15: 0x0000000000000000
  rip: <unavailable>       rfl: 0x0000000000000202
 tmp0: 0x0000000116f69b38 tmp1: 0x0000000000000215 tmp2: 0x000000010f1a2740


Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x116f3a000 -        0x1173c0fff libswiftCore.dylib (*) <432ab6bf-6689-3faa-a276-3476ba7d9912> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/swift/libswiftCore.dylib
       0x104ff2000 -        0x105b01fff org.reactjs.native.example.RNMapboxGLExample (1.0) <41a00828-0f74-34ae-8223-e6240cb9f74c> /Users/USER/Library/Developer/CoreSimulator/Devices/C276C5CB-97F6-4816-A1BD-DF1433F9702C/data/Containers/Bundle/Application/BA4E62F7-B6E3-456C-BB13-B550DAF2A704/RNMapboxGLExample.app/RNMapboxGLExample
       0x11534d000 -        0x115393fff libdispatch.dylib (*) <a1e15d82-e95a-30ec-832e-288d5d2c9a5f> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib
       0x112187000 -        0x11258cfff com.apple.CoreFoundation (6.9) <d7b873d0-2d44-362d-a632-91b54d2dd8c2> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x118113000 -        0x11811bfff com.apple.GraphicsServices (1.0) <d645c3c0-b4f8-31d0-bada-02aea61681d5> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x121aa9000 -        0x123337fff com.apple.UIKitCore (1.0) <f710b655-42ee-3939-a3bd-6da0f3758758> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x1103ff000 -        0x11044cfff dyld_sim (*) <7276a69b-e3b9-3f23-957f-061350a501b4> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/dyld_sim
       0x208005000 -        0x208070fff dyld (*) <f71fb3ca-5fcc-3577-9457-b047888a46d1> /usr/lib/dyld
       0x117984000 -        0x1179bbfff libsystem_kernel.dylib (*) <a8ff3bd6-3ce8-3eee-813d-8a9202478b49> /usr/lib/system/libsystem_kernel.dylib
       0x114136000 -        0x11442afff com.apple.Foundation (6.9) <9827fa7d-2500-32d7-aaaf-288e38b126ab> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
       0x11789a000 -        0x1178a5fff libsystem_pthread.dylib (*) <f32b6d06-b156-3da0-b086-a31cf011362b> /usr/lib/system/libsystem_pthread.dylib
       0x111bdd000 -        0x112062fff com.apple.CFNetwork (1333.0.4) <c7736999-25a1-3906-878f-42129a17778b> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CFNetwork.framework/CFNetwork
       0x11546b000 -        0x116a99fff com.apple.JavaScriptCore (8613) <c3dd861c-20c9-3f06-ba09-a3e8537c3a6b> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
       0x110306000 -        0x11035bfff libc++.1.dylib (*) <cca55188-d9dc-33ae-b968-d9a6600c9cbe> /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libc++.1.dylib
       0x111385000 -        0x111570fff com.mapbox.common (22.0.0) <4239db26-ed92-3ca7-9cd1-0638db8b6248> /Users/USER/Library/Developer/CoreSimulator/Devices/C276C5CB-97F6-4816-A1BD-DF1433F9702C/data/Containers/Bundle/Application/BA4E62F7-B6E3-456C-BB13-B550DAF2A704/RNMapboxGLExample.app/Frameworks/MapboxCommon.framework/MapboxCommon
````

**Expected behavior**  
No crash

**Actual behavior**  
App crashes

**Screenshots**  

https://user-images.githubusercontent.com/6340397/180285552-cd36fc2f-9961-4d5a-9abe-7e7b2a3596ad.mp4

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: iOS 15
 - Device: simulated iPhone 13
 - Emulator/ Simulator: yes (not tested on real device yet)
 - Dev OS: macOS 12.5
 - @rnmapbox/maps Version: main branch, 6d266f7c3d707941a380733630b1dbf561780c48
 - Mapbox GL version v10
 - React Native Version 0.68.1

### PR DESCRIPTION
**Pull request by mysport12**
## Description

Fixes #2062

Add nil check when adding/removing map subviews to avoid crash

## Checklist

- [x] I have tested this on a device/simulator for each compatible OS
- [ ] I updated the documentation with running `yarn generate` in the root folder
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typings files (`index.d.ts`)
- [ ] I added/ updated a sample (`/example`)

### CODE REVIEW

File: ios/RCTMGL-v10/RCTMGLMapView.swift [hunk 1]
```diff
@@ -50,7 +50,9 @@ open class RCTMGLMapView : MapView {
       }
     } else {
       print("addToMap.Subviews: \(subview.reactSubviews())")
-      subview.reactSubviews().forEach { addToMap($0) }
+      if (subview.reactSubviews() != nil) {
+        subview.reactSubviews().forEach { addToMap($0) }
+      }
```
Comment (mfazekas) [inline ios/RCTMGL-v10/RCTMGLMapView.swift:55]:
```suggestion
      subview.reactSubviews()?.forEach { addToMap($0) }
```

File: ios/RCTMGL-v10/RCTMGLMapView.swift [hunk 2]
```diff
@@ -64,7 +66,9 @@ open class RCTMGLMapView : MapView {
       }
       mapComponent.removeFromMap(self)
     } else {
-      subview.reactSubviews().forEach { removeFromMap($0) }
+      if (subview.reactSubviews() != nil) {
+        subview.reactSubviews().forEach { removeFromMap($0) }
+      }
```
Comment (mfazekas) [inline ios/RCTMGL-v10/RCTMGLMapView.swift:71]:
```suggestion
      subview.reactSubviews()?.forEach { removeFromMap($0) }
```

File: ios/RCTMGL-v10/RCTMGLMapView.swift [hunk 3]
```diff
@@ -50,7 +50,9 @@ open class RCTMGLMapView : MapView {
       }
     } else {
       print("addToMap.Subviews: \(subview.reactSubviews())")
```
Comment (mfazekas) [inline ios/RCTMGL-v10/RCTMGLMapView.swift:52]: Can you remove this log line, too?!

**Review by mfazekas — CHANGES_REQUESTED** [review]
Thanks much! I think we can use the optional chaining operator in swift for this.

File: ios/RCTMGL-v10/RCTMGLMapView.swift (hunk 1 above)
Comment (mysport12) [reply ios/RCTMGL-v10/RCTMGLMapView.swift]: Fixed!

File: ios/RCTMGL-v10/RCTMGLMapView.swift (hunk 2 above)
Comment (mysport12) [reply ios/RCTMGL-v10/RCTMGLMapView.swift]: Fixed!

File: ios/RCTMGL-v10/RCTMGLMapView.swift (hunk 3 above)
Comment (mysport12) [reply ios/RCTMGL-v10/RCTMGLMapView.swift]: Done!
